require "RECIPES.pm";
@myFileList=("typesdef.f90",
             "communicate.f90",
             "basis.f90",
             "toleranceBasis.f90",
             "movemesh.f90",
             "pointerbasis.f90",
             "curved.f90",
             "isovaryingstring.f90",
             "maxwell.f90",
             "nodal.f90",
             "io_visu.f90",
             "io_restart.f90",
             "io_tools.f90",
             "meshbasis.f90",
             "adaptive.f90",
             "dg.f90",
             "mesh.f90",
             "search.f90",
             "postproc.f90",
             "setup.f90",
             "timedisc_gts.f90",
             "headers.f90",
             "HALO.f90");

push(@flist,@myFileList);
