before_script:
  - export PATH=/opt/openmpi/4.1.0/bin:$PATH
  - export LD_LIBRARY_PATH=/opt/openmpi/4.1.0/lib/:$LD_LIBRARY_PATH
  - export CMAKE_PREFIX_PATH=/opt/openmpi/4.1.0/share/cmake:$CMAKE_PREFIX_PATH
  - export CMAKE_LIBRARY_PATH=/opt/openmpi/4.1.0/lib:$CMAKE_LIBRARY_PATH
  - export HDF5_DIR=/opt/hdf5/1.12.0/share/cmake/
  - export LD_LIBRARY_PATH=/opt/hdf5/1.12.0/lib/:$LD_LIBRARY_PATH
  - export CMAKE_PREFIX_PATH=/opt/hdf5/1.12.0/:$CMAKE_PREFIX_PATH
  - export CMAKE_LIBRARY_PATH=/opt/hdf5/1.12.0/lib:$CMAKE_LIBRARY_PATH

stages:
  - build
  - error_clean
  - test
  - documentation
  - deploy

cache:
  key: "$CI_BUILD_REF"
  paths: 
    - build_gnu/
    - doc/doxygen/doxygen
    - doc/Meshformat/Meshformat.pdf


build_gnu:
  stage: build
  tags:
    - flexitag
  script:
    - mkdir -p build_gnu ; cd build_gnu
    - if [ -n "${DO_NIGHTLY}" ]; then cmake .. ; fi
    - if [ -z "${DO_NIGHTLY}" ]; then cmake .. -DHOPR_BUILD_HDF5=OFF ; fi
    - make all

clean:
  stage: error_clean
  tags:
    - flexitag
  script:
    - rm -rf build_gnu
    - rm -rf share
  when: on_failure

run_gnu:
  stage: test
  tags:
    - flexitag
  script:
    - cd tutorials ; ./executeall.sh ../build_gnu/bin/hopr

doxygen:
  stage: documentation
  tags:
    - flexitag
  script:
    - cd doc/doxygen ; ./builddoxy.sh

meshformat:
  stage: documentation
  tags:
    - flexitag
  script:
    - cd doc/Meshformat ; make

deploy_homepage:
  stage: deploy
  tags:
    - flexitag
  script:
    - if [ -n "${DO_DEPLOY}" ]; then if [ -d "doc/doxygen/doxygen" ]; then ssh flexi@euler rm -rf homepage_hopr/doxygen ; scp -r doc/doxygen/doxygen flexi@euler:~/homepage_hopr/. ; fi ; fi
    - if [ -n "${DO_DEPLOY}" ]; then if [ -f "doc/Meshformat/Meshformat.pdf" ]; then scp doc/Meshformat/Meshformat.pdf flexi@euler:~/homepage_hopr/. ; fi ; fi

deploy_github:
  stage: deploy
  tags:
    - flexitag
  script:
    - if [ -z "${DO_DEPLOY}" ]; then exit ; fi
    - git clone --single-branch git@gitlab.iag.uni-stuttgart.de:hopr/hopr.git hopr_github ; cd hopr_github ; git push --mirror git@github.com:flexi-framework/hopr.git ; cd ../
